# The site blueprint must have a title, the title may be different from the file name
# The `site.yml` blueprint defines the look of the start page (Dashboard) of the Panel.
title: Site

# The site blueprint usually provides easy access to all main pages of the site.
# In this example blueprint, we also show subpages of the `photography` and `notes` pages.
# More about the site blueprint: https://getkirby.com/docs/reference/panel/blueprints/site

# The layout of this form has two columns:
columns:
  # The first column has one section for the subpages of the `photography` page in card layout
  # It reuses the pages section defined in `/site/blueprints/sections/albums.yml`
  - width: 2/3
    sections:
      drafts:
        extends: sections/albums
        headline: Drafts
        status: draft
      featured:
        headline: Featured Projects
        type: pagesdisplay
        query: site.index.filterBy("category", "featured", ",")
        layout: cards
        size: tiny
        info: "{{ page.category }}"
        template: album
        empty: No albums yet
        image:
          query: page.cover
          cover: true
          ratio: 5/4
      recent:
        headline: Recent Projects
        type: pagesdisplay
        query: site.index.filterBy("category", "recent", ",")
        layout: cards
        size: tiny
        info: "{{ page.category }}"
        template: album
        empty: No albums yet
        image:
          query: page.cover
          cover: true
          ratio: 5/4
      archive:
        headline: Archive Projects
        type: pagesdisplay
        query: site.index.filterBy("category", "archive", ",")
        layout: list
        info: "{{ page.category }}"
        template: album
        empty: No albums yet
#        image:
#          query: page.cover
#          cover: true
#          ratio: 5/4
#      albums: sections/albums

  # The second column has two sections, `notes` and `pages`
  - width: 1/3
    sections:
      # The `notes` section reuses the pages section defined in `/site/blueprints/sections/notes.yml`
      #notes: sections/notes

      # The `pages` pages section shows other main pages of the site
      # Using the `templates` option, we limit which types of pages are shown
      # Using the `create` option, we limit the type of page that can be created when a new page is created
      # Note that the `sandbox` page and the `error` page that also exist in the content folder but use different blueprints thus do not show up in the list
      # Since the error page's blueprint is set to `read: false`, it wouldn't show up here even if you added the error blueprint to the templates list
      about: 
        type: fields 
        fields:
            agency:
              label: Agency About Text
              type: textarea
              size: small
              buttons: false
              required: true
            agencyimage:
              label: Agency Image
              type: files
              max: 1
              cover: true
              ratio: 1/1
              required: true
            clients:
              label: Clients
              type: structure
              fields:
                client:
                  label: Client Name
                  type: text
            address:
              label: Address
              type: textarea
              required: true
            email:
              label: Contact Email
              type: email
              required: true
            phone:
              label: Contact Phone
              type: tel
              required: true
            social:
              label: Social
              type: structure
              fields:
                platform:
                  label: Platform
                  type: text
                  width: 1/3
                url:
                  label: URL
                  type: url
                  width: 2/3
            